name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # This is a complicated set of strategies, but Elixir has a complicated set of supported versions.
    # See https://hexdocs.pm/elixir/compatibility-and-deprecations.html
    # See https://hexdocs.pm/elixir/compatibility-and-deprecations.html#between-elixir-and-erlang-otp
    #
    # NOTE: We're intentionally not including Elixir 1.14.x + OTP 23.x
    # because erlef/setup-beam@v1 doesn't support it.
    strategy:
      matrix:
        elixir-version: ["1.15.x", "1.16.x", "1.17.x", "1.18.x"]
        otp-version: ["24.x", "25.x", "26.x", "27.x"]
        exclude:
          # Elixir 1.17 and 1.18 don't support OTP 24
          - elixir-version: "1.17.x"
            otp-version: "24.x"
          - elixir-version: "1.18.x"
            otp-version: "24.x"
          # Elixir 1.15 and 1.16 don't support OTP 27
          - elixir-version: "1.15.x"
            otp-version: "27.x"
          - elixir-version: "1.16.x"
            otp-version: "27.x"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir ${{ matrix.elixir-version }} / OTP ${{ matrix.otp-version }}
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Run security audit
        run: mix deps.audit

  dialyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-dialyzer-

      - name: Restore PLT cache
        uses: actions/cache@v4
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-plt-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Create PLTs
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Generate documentation
        run: mix docs

      - name: Check documentation coverage
        run: |
          if [ -d "doc" ]; then
            echo "Documentation generated successfully"
          else
            echo "Documentation generation failed"
            exit 1
          fi
